id: I8375A3A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T22:27:48+00:00'
last_modified: '2022-06-08T17:30:08.861094+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1147
  title: ངན་སོང་སྦྱོང་རྒྱུད་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3959':
      image_group_id: I1CZ1558
      title: ''
      total_pages: 124
      order: 1
      base_file: 3959.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
